
process Igblast_chain_check {
    label 'r_ig_clustering'
    publishDir path: "${out_path}/reports", mode: 'copy', pattern: "{igblast_chain_check.log}", overwrite: false
    cache 'true'

    input:
    path productive_ch // no parallelization
    path allele_names_tsv_all_ch // to have all the files in the work dir
    val igblast_v_ref_files 
    val igblast_d_ref_files 
    val igblast_j_ref_files 
    val igblast_constant_ref_files 
    path cute_file
    val nb_productive

    when:
    nb_productive > 0

    output:
    path "selected.tsv", emit: checked_tsv_ch
    path "not_selected.tsv", emit: not_checked_tsv_ch
    path "igblast_chain_check.log", emit: igblast_chain_check_log

    script:
    """
    #!/bin/bash -ue
    set -o pipefail
    # igblast_data_check_ch not required here
    echo -e "\\n\\n\$PWD\\n" |& tee -a igblast_chain_check.log
    echo -e "${productive_ch}\\n\\n" |& tee -a igblast_chain_check.log
    # if [[ ! -s ${productive_ch} ]]; then # -s means "exists and non empty". Thus, return FALSE is the file does not exists or is empty
        # echo -e "\\n\\n========\\n\\nINTERNAL ERROR IN NEXTFLOW EXECUTION\\n\\nEMPTY FILE GENERATED BY THE ParseDb_filtering PROCESS.\\nCHECK THE igblast_chain_check.log FILE IN THE report FOLDER INSIDE THE OUTPUT FOLDER.\\n\\nPLEASE, REPORT AN ISSUE HERE https://gitlab.pasteur.fr/gmillot/repertoire_profiler/-/issues OR AT gael.millot<AT>pasteur.fr.\\n\\n========\\n\\n" # I said empty because the existence of the file has been checked after the igblast process
        # exit 1
    # fi
    igblast_chain_check.R \
"${productive_ch}" \
"${igblast_v_ref_files}" \
"${igblast_d_ref_files}" \
"${igblast_j_ref_files}" \
"${igblast_constant_ref_files}" \
"${cute_file}" \
"igblast_chain_check.log"
    """
}